environment:
  matrix:
    - nodejs_version: "7.7.4"

matrix:
  fast_finish: true

install:
  - ps: Install-Product node $env:nodejs_version
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run test -- --watch=false
  - npm run e2e

build: off

cache:
  - node_modules -> package-lock.json